spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:root}
    username: ${MYSQL_USERNAME:root}
    url: jdbc:mysql://localhost/hello-sealos?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
